// Code generated by fertilize; DO NOT EDIT.
package bible

import (
  	"encoding/json"
	"fmt"
	"git.launchpad.net/~man4christ/+git/seed/server"
	"git.launchpad.net/~man4christ/+git/seed/validate"
) 
 
// SearchHandler validates input data prior to calling Search
func (h BibleSearchServicer) SearchHandler(r server.GenericRequest, b []byte) (any, error) {
	var hr BibleSearchRequest
	if err := json.Unmarshal(b, &hr); err != nil {
		return nil, fmt.Errorf("Unmarshalling data: %w", err)
	}

	if err := validate.Check(hr); err != nil {
		return nil, fmt.Errorf("validating data: %w", err)
	}

	return h.Search(hr, r), nil
}
